apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://qdrant.github.io/qdrant-helm
    chart: qdrant
    targetRevision: 1.13.6
    helm:
      parameters:
        - name: persistence.storageClassName
          value: longhorn
        - name: persistence.size
          value: 50Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: rag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
